import './globals.css'
import { Inter } from 'next/font/google'

import SessionProvider from './SessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'vaibhav-giphy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full">
      <SessionProvider>
        
        {children}
      </SessionProvider>
      </body>
    </html>
  )
}
